version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: biznes-vokrug
    environment:
      POSTGRES_DB: biznes-vokrug
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "54323:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  minio:
    image: minio/minio:latest
    container_name: minio_biz_vokr
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always


volumes:
  pgdata:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local

networks:
  backend_network:
    driver: bridge
