version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: biznes-vokrug
    environment:
      POSTGRES_DB: biznes-vokrug
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local