"""empty message

Revision ID: 3afed5165076
Revises: 5587e3b14311
Create Date: 2024-11-12 15:29:54.821722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afed5165076'
down_revision: Union[str, None] = '5587e3b14311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations_models', 'dadata_suggestions')
    op.add_column('owners_models', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners_models', 'hashed_password')
    op.add_column('organizations_models', sa.Column('dadata_suggestions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
