"""empty message

Revision ID: 83626956c2ce
Revises: e936bda96d4f
Create Date: 2025-01-09 16:39:45.494751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83626956c2ce'
down_revision: Union[str, None] = 'e936bda96d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_models', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products_models', 'product_categories', ['category_id'], ['id'])
    op.add_column('services_models', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services_models', 'service_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services_models', type_='foreignkey')
    op.drop_column('services_models', 'category_id')
    op.drop_constraint(None, 'products_models', type_='foreignkey')
    op.drop_column('products_models', 'category_id')
    # ### end Alembic commands ###
