"""empty message

Revision ID: 8b8e6e9363d9
Revises: 
Create Date: 2024-06-22 21:12:37.553187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8e6e9363d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memes_models_id'), 'memes_models', ['id'], unique=False)
    op.create_index(op.f('ix_memes_models_title'), 'memes_models', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_models_title'), table_name='memes_models')
    op.drop_index(op.f('ix_memes_models_id'), table_name='memes_models')
    op.drop_table('memes_models')
    # ### end Alembic commands ###
