"""empty message

Revision ID: 96e83561ff00
Revises: a17ecd8065c4
Create Date: 2025-01-10 15:25:33.156721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e83561ff00'
down_revision: Union[str, None] = 'a17ecd8065c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_entrepreneurs_models', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('individual_entrepreneurs_models', 'name')
    # ### end Alembic commands ###
