"""empty message

Revision ID: 97a3eeb6bd84
Revises: 3afed5165076
Create Date: 2024-11-12 16:22:53.688127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a3eeb6bd84'
down_revision: Union[str, None] = '3afed5165076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_entrepreneurs_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(), nullable=False),
    sa.Column('ogrnip', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('ogrnip')
    )
    op.create_index(op.f('ix_individual_entrepreneurs_models_id'), 'individual_entrepreneurs_models', ['id'], unique=False)
    op.add_column('organizations_models', sa.Column('inn', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('ogrn', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('owners_models', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners_models', 'phone')
    op.drop_column('organizations_models', 'phone')
    op.drop_column('organizations_models', 'ogrn')
    op.drop_column('organizations_models', 'inn')
    op.drop_index(op.f('ix_individual_entrepreneurs_models_id'), table_name='individual_entrepreneurs_models')
    op.drop_table('individual_entrepreneurs_models')
    # ### end Alembic commands ###
