"""empty message

Revision ID: d4395c23ca51
Revises: 97a3eeb6bd84
Create Date: 2024-11-13 14:57:41.304821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4395c23ca51'
down_revision: Union[str, None] = '97a3eeb6bd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations_models', sa.Column('website', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('email', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('category', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('organizations_models', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('organizations_models', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('city', sa.String(), nullable=True))
    op.add_column('organizations_models', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('organizations_models', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations_models', 'updated_at')
    op.drop_column('organizations_models', 'created_at')
    op.drop_column('organizations_models', 'city')
    op.drop_column('organizations_models', 'logo_url')
    op.drop_column('organizations_models', 'rating')
    op.drop_column('organizations_models', 'is_verified')
    op.drop_column('organizations_models', 'category')
    op.drop_column('organizations_models', 'email')
    op.drop_column('organizations_models', 'website')
    # ### end Alembic commands ###
