"""empty message

Revision ID: f910988ebb83
Revises: d6225d28a19a
Create Date: 2024-11-14 15:49:23.807349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f910988ebb83'
down_revision: Union[str, None] = 'd6225d28a19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('individual_entrepreneur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individual_entrepreneur_id'], ['individual_entrepreneurs_models.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_models_id'), 'products_models', ['id'], unique=False)
    op.create_table('services_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('individual_entrepreneur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['individual_entrepreneur_id'], ['individual_entrepreneurs_models.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_models_id'), 'services_models', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_models_id'), table_name='services_models')
    op.drop_table('services_models')
    op.drop_index(op.f('ix_products_models_id'), table_name='products_models')
    op.drop_table('products_models')
    # ### end Alembic commands ###
